In [27]:
import pandas as pd 
# 数据库
from sqlalchemy import create_engine
engine = create_engine('mysql://root:root@localhost:3306/citylist?charset=utf8')
# stock_basic.to_sql('stock_basic',engine,index=False,if_exists='append')

In [4]:
import os
f = [c for c in os.listdir('../长三角城市年度数据')]

['上海市_113个指标.xls',
 '安徽省合肥_111个指标.xls',
 '安徽省安庆_112个指标.xls',
 '安徽省宣城_112个指标.xls',
 '安徽省池州_112个指标.xls',
 '安徽省滁州_112个指标.xls',
 '安徽省芜湖_112个指标.xls',
 '安徽省铜陵_112个指标.xls',
 '安徽省马鞍山_111个指标.xls',
 '江苏省南京市_113个指标.xls',
 '江苏省南通市_113个指标.xls',
 '江苏省常州市_113个指标.xls',
 '江苏省扬州市_113个指标.xls',
 '江苏省无锡市_113个指标.xls',
 '江苏省泰州_113个指标.xls',
 '江苏省盐城市_113个指标.xls',
 '江苏省苏州市_113个指标.xls',
 '江苏省镇江市_113个指标.xls',
 '浙江省台州_112个指标.xls',
 '浙江省嘉兴_113个指标.xls',
 '浙江省宁波_113个指标.xls',
 '浙江省杭州_113个指标.xls',
 '浙江省温州_113个指标.xls',
 '浙江省湖州_112个指标.xls',
 '浙江省绍兴_112个指标.xls',
 '浙江省舟山_112个指标.xls',
 '浙江省金华_112个指标.xls']

In [47]:
df =pd.DataFrame()
for file in f:
    data = pd.read_excel('../长三角城市年度数据/'+file)
    localname = data.iloc[0,1]
    data['name']= localname
    data.drop(index=[0,1,2],inplace=True)
    col_name = data.columns.values
    col_name[0] = 'year'
    data.columns = col_name
    print(data.shape,localname)
    data.to_sql('city_data2',engine,index=False,if_exists='append')

(24, 115) 上海市
(24, 113) 合肥市
(24, 114) 安庆市
(18, 114) 宣城市
(18, 114) 池州市
(24, 114) 滁州市
(24, 114) 芜湖市
(24, 114) 铜陵市
(24, 113) 马鞍山市
(24, 115) 南京市
(24, 115) 南通市
(24, 115) 常州市
(24, 115) 扬州市
(24, 115) 无锡市
(24, 115) 泰州市
(24, 115) 盐城市
(24, 115) 苏州市
(24, 115) 镇江市
(24, 114) 台州市
(24, 115) 嘉兴市
(24, 115) 宁波市
(24, 115) 杭州市
(24, 115) 温州市
(24, 114) 湖州市
(24, 114) 绍兴市
(24, 114) 舟山市
(24, 114) 金华市

In [29]:
data.head()

,year,城市道路面积,城市工业生产用电量,城市公园绿地面积,城市供水总量,城市户籍人口数,城市建成区绿化覆盖率,城市建成区绿化覆盖面积,城市建成区面积,城市建设用地面积,...,医疗卫生机构床位数_医院和卫生院_市辖区,医疗卫生机构数_医院和卫生院_市辖区,医院和卫生院卫生人员数_执业(助理)医师_市辖区,职工基本医疗保险参保人数_市辖区,中等职业教育学校数_市辖区,中等职业教育在校生数_市辖区,中等职业教育专任教师数_市辖区,GDP_市辖区,GDP实际增速_市辖区,name
3,1994,3179,NaN,NaN,355796,953.04,NaN,NaN,350,NaN,...,53087,321,46151,NaN,NaN,NaN,NaN,15220000,NaN,上海市
4,1995,NaN,NaN,NaN,294047,956.66,16.6,NaN,390,NaN,...,52503,310,44507,NaN,NaN,NaN,NaN,19693200,NaN,上海市
5,1996,NaN,NaN,NaN,295310,961.02,17.2,NaN,412,NaN,...,52839,303,43370,NaN,NaN,NaN,NaN,23335200,NaN,上海市
6,1997,4268,NaN,NaN,288182,1018.59,18.6,NaN,412,NaN,...,55727,323,43813,NaN,NaN,NaN,NaN,26994700,NaN,上海市
7,1998,5401,NaN,NaN,292825,1070.62,15.5,NaN,550,NaN,...,58727,349,44217,NaN,NaN,NaN,NaN,29732600,NaN,上海市

In [28]:
data.columns

Index(['year', '城市道路面积', '城市工业生产用电量', '城市公园绿地面积', '城市供水总量', '城市户籍人口数',
       '城市建成区绿化覆盖率', '城市建成区绿化覆盖面积', '城市建成区面积', '城市建设用地面积',
       ...
       '一般公共预算支出_市辖区', '医疗卫生机构床位数_医院和卫生院_市辖区', '医疗卫生机构数_医院和卫生院_市辖区',
       '医院和卫生院卫生人员数_执业(助理)医师_市辖区', '职工基本医疗保险参保人数_市辖区', '中等职业教育学校数_市辖区',
       '中等职业教育在校生数_市辖区', '中等职业教育专任教师数_市辖区', 'GDP_市辖区', 'GDP实际增速_市辖区'],
      dtype='object', length=114)

In [42]:
sql = "select * from city_data where year='2001'"
data1997 = pd.read_sql(sql,engine)
data1997

,year,城市道路面积,城市工业生产用电量,城市公园绿地面积,城市供水总量,城市户籍人口数,城市建成区绿化覆盖率,城市建成区绿化覆盖面积,城市建成区面积,城市建设用地面积,...,医疗卫生机构床位数_医院和卫生院_市辖区,医疗卫生机构数_医院和卫生院_市辖区,医院和卫生院卫生人员数_执业(助理)医师_市辖区,职工基本医疗保险参保人数_市辖区,中等职业教育学校数_市辖区,中等职业教育在校生数_市辖区,中等职业教育专任教师数_市辖区,GDP_市辖区,GDP实际增速_市辖区,name
0,2001,13411,None,None,296110,1262.41,25.8,None,550,None,...,73055,402,35618,None,None,None,None,48930100,None,上海市
1,2001,1356,None,None,20019,137.95,33.9,None,125,None,...,9423,72,5855,None,None,None,None,2692992,None,合肥市
2,2001,498,None,None,25053,58.18,28.5,None,31,None,...,2897,27,1232,None,None,None,None,710470,None,安庆市
3,2001,147,None,None,1657,83.46,35.6,None,18,None,...,1396,41,622,None,None,None,None,559422,None,宣城市
4,2001,110,None,None,1389,62.09,27.9,None,12,None,...,1079,28,537,None,None,None,None,311247,None,池州市
5,2001,260,None,None,2519,49.42,37.4,None,21,None,...,1793,28,909,None,None,None,None,573602,None,滁州市
6,2001,536,None,None,16717,65.88,32,None,71,None,...,3904,35,2178,None,None,None,None,1318405,None,芜湖市
7,2001,285,None,None,18286,35.64,38.6,None,33,None,...,2280,16,1219,None,None,None,None,635784,None,铜陵市
8,2001,460,None,None,45585,52.93,42.5,None,38,None,...,2516,18,1559,None,None,None,None,1102075,None,马鞍山市
9,2001,4568,None,None,125667,371.89,42.7,None,212,None,...,17909,225,9157,None,None,None,None,9817597,None,南京市
10,2001,425,None,None,10766,79.54,31.5,None,73,None,...,4982,33,1995,None,None,None,None,1901962,None,南通市
11,2001,1024,None,None,20123,89.47,31.8,None,71,None,...,4968,29,2316,None,None,None,None,2258806,None,常州市
12,2001,512,None,None,10540,109.66,34.9,None,53,None,...,4140,45,1801,None,None,None,None,2325220,None,扬州市
13,2001,3561,None,None,23902,213.07,29.6,None,164,None,...,9611,77,3856,None,None,None,None,8005606,None,无锡市
14,2001,352,None,None,5193,60.57,25.8,None,40,None,...,1867,19,1129,None,None,None,None,1239651,None,泰州市
15,2001,357,None,None,7634,63.93,24.3,None,43,None,...,2011,20,963,None,None,None,None,770747,None,盐城市
16,2001,1205,None,None,19474,209.46,33.3,None,109,None,...,7335,1,3832,None,None,None,None,6185600,None,苏州市
17,2001,792,None,None,12754,62.82,35.3,None,63,None,...,3272,23,1440,None,None,None,None,1648822,None,镇江市
18,2001,1187,None,None,9329,143.9,13.8,None,81,None,...,3266,85,1958,None,None,None,None,2833478,None,台州市
19,2001,615,None,None,6232,79.11,25.6,None,46,None,...,2645,37,1241,None,None,None,None,1406002,None,嘉兴市
20,2001,1054,None,None,26419,126.13,34.6,None,74,None,...,6309,71,4198,None,None,None,None,5813159,None,宁波市
21,2001,1941,None,None,52000,379.49,34.7,None,227,None,...,17770,191,12968,None,None,None,None,11951694,None,杭州市
22,2001,911,None,None,20285,131.36,21.4,None,111,None,...,5524,97,1595,None,None,None,None,3883859,None,温州市
23,2001,552,None,None,6417,107.52,24.8,None,55,None,...,3536,36,1963,None,None,None,None,1826697,None,湖州市
24,2001,424,None,None,7023,59.92,38.1,None,35,None,...,2251,20,1170,None,None,None,None,1277314,None,绍兴市
25,2001,303,None,None,3910,68.85,44.6,None,55,None,...,2239,56,1586,None,None,None,None,869560,None,舟山市
26,2001,347,None,None,5593,91.34,20.5,None,49,None,...,3094,56,1650,None,None,None,None,1058028,None,金华市